//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentMasterApi.Models
{
    using System;
    using Microsoft.EntityFrameworkCore;
    using System.Linq;
    using MySql.Data.EntityFrameworkCore.Migrations;
    
    public class employmentEntities : DbContext
    {
        public employmentEntities(DbContextOptions options)
            : base(options)
        {
        }
    
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }
    
        public virtual DbSet<employee_recruit> employee_recruit { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<version> versions { get; set; }
        
    }
}
