//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wepapi_core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_recruit
    {
        public string Id { get; set; }
        public long intv_no { get; set; }
        public string f_name { get; set; }
        public string m_name { get; set; }
        public string l_name { get; set; }
        public string qualification { get; set; }
        public string school { get; set; }
        public string adr1 { get; set; }
        public string adr2 { get; set; }
        public string adr3 { get; set; }
        public string st_no { get; set; }
        public string st_name { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string pin { get; set; }
        public string employment_type { get; set; }
        public Nullable<System.DateTime> interview_date { get; set; }
        public string online_diary_no { get; set; }
        public string dispatch_no { get; set; }
        public Nullable<System.DateTime> join_date { get; set; }
        public Nullable<System.DateTime> dated { get; set; }
        public string gen_applied_post { get; set; }
        public string gen_basic_pay { get; set; }
        public string gen_pay_scale_level { get; set; }
        public string gen_payscale { get; set; }
        public string addhoc_net_salary { get; set; }
        public string addhoc_tenure { get; set; }
        public Nullable<System.DateTime> addhoc_from_date { get; set; }
        public Nullable<System.DateTime> addhoc_to_date { get; set; }
    }
}
