//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentMasterApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string id { get; set; }
        public string f_name { get; set; }
        public string m_name { get; set; }
        public string l_name { get; set; }
        public string p_address { get; set; }
        public string l_address { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
    }
}
