//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wepapi_core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class version
    {
        public int id { get; set; }
        public long version1 { get; set; }
        public System.DateTime update_time { get; set; }
    }
}
