// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentMasterApi.Models;

namespace wepapi_core.Data.Migration
{
    [DbContext(typeof(employmentEntities))]
    [Migration("20190908175421_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("RecruitmentMasterApi.Models.employee_recruit", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("addhoc_from_date");

                    b.Property<string>("addhoc_net_salary");

                    b.Property<string>("addhoc_tenure");

                    b.Property<DateTime?>("addhoc_to_date");

                    b.Property<string>("adr1");

                    b.Property<string>("adr2");

                    b.Property<string>("adr3");

                    b.Property<string>("city");

                    b.Property<DateTime?>("dated");

                    b.Property<string>("dispatch_no");

                    b.Property<string>("employment_type");

                    b.Property<string>("f_name");

                    b.Property<string>("gen_applied_post");

                    b.Property<string>("gen_basic_pay");

                    b.Property<string>("gen_pay_scale_level");

                    b.Property<string>("gen_payscale");

                    b.Property<DateTime?>("interview_date");

                    b.Property<long>("intv_no");

                    b.Property<DateTime?>("join_date");

                    b.Property<string>("l_name");

                    b.Property<string>("m_name");

                    b.Property<string>("online_diary_no");

                    b.Property<string>("pin");

                    b.Property<string>("qualification");

                    b.Property<string>("school");

                    b.Property<string>("st_name");

                    b.Property<string>("st_no");

                    b.Property<string>("state");

                    b.HasKey("Id");

                    b.ToTable("employee_recruit");
                });

            modelBuilder.Entity("RecruitmentMasterApi.Models.user", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("f_name");

                    b.Property<string>("l_address");

                    b.Property<string>("l_name");

                    b.Property<string>("m_name");

                    b.Property<string>("p_address");

                    b.Property<string>("phone");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("RecruitmentMasterApi.Models.version", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("update_time");

                    b.Property<long>("version1");

                    b.HasKey("id");

                    b.ToTable("versions");
                });
#pragma warning restore 612, 618
        }
    }
}
